# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-03 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialer_campaign', '0002_campaign_stoppeddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='aleg_gateway',
            field=models.ForeignKey(help_text='select outbound gateway', on_delete=django.db.models.deletion.CASCADE, related_name='ALegGateway', to='dialer_gateway.Gateway', verbose_name='A-Leg gateway'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='calltimeout',
            field=models.IntegerField(blank=True, default=b'45', help_text='dialing timeout in seconds', null=True, verbose_name='timeout on dialing'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Campaignowner', to=settings.AUTH_USER_MODEL),
        ),
    ]
