# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-03 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialer_cdr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrequest',
            name='timeout',
            field=models.IntegerField(blank=True, default=30, verbose_name='dialing time out'),
        ),
        migrations.AlterField(
            model_name='voipcall',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CallSender', to=settings.AUTH_USER_MODEL),
        ),
    ]
